name: ci

on:
  pull_request:
    branches:
      - "master"
  push:
    branches:
      - "master"
env:
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-objects-build-project-build-docker-push-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      
    # check for pull_requests:
    if: github.event_name != 'pull_request' || github.event.action == 'closed'
    
    steps:
    - name: Checkout etutor-objects
      uses: actions/checkout@v2
      with:
        repository: eTutor-plus-plus/objects
        ref: main
        path: objects
        
    - name: Build objects with Maven
      run: mvn clean install -f objects
   
    - name: Checkout platform
      uses: actions/checkout@v3
      with:
        path: repo
        
    - name: Set up JDK 17
      uses: actions/setup-java@v1
      with:
        java-version: 17
        
    - name: Build project with Maven
      working-directory: repo
      run: mvn -Pprod -B package

    - name: Log in to the Docker Hub
      uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
      with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
    
    - name: Extract metadata (tags, labels) for Docker
      id: meta
      uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
      with:
        images: ${{ secrets.DOCKER_NAMESPACE }}/platform
        
    - name: Set date
      run: |
        echo "DATE=$(date +%Y%m%d)" >> $GITHUB_ENV
        
    - name: Build and push Docker image
      uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
      with:
        context: ./repo
        push: true
        tags: ${{ secrets.DOCKER_NAMESPACE }}/platform:main-${{ env.DATE }}
        labels: ${{ steps.meta.outputs.labels }}
